/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FileEvent {
  path: string
  eventType: string
}
export interface WatchOptions {
  recursive?: boolean
  ignorePaths?: Array<string>
}
export declare class FileWatcher {
  constructor()
  watchPath(path: string, onEvent: (...args: any[]) => any, options?: WatchOptions | undefined | null): void
  unwatchPath(path: string): boolean
  getWatchedPaths(): Array<string>
  isWatching(path: string): boolean
  unwatchAll(): boolean
}
