/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FileEntry {
  name: string
  path: string
  isDir: boolean
  isFile: boolean
  size?: number
  children?: Array<FileEntry>
}
export interface FileEvent {
  path: string
  kind: string
}
export declare function openProject(path: string): FileEntry
export declare function watchProject(path: string, callback: (err: Error | null, arg: FileEvent) => any): void
export declare function stopWatching(path: string): boolean
export declare function getDirectoryContents(path: string): Array<FileEntry>
export declare function readFileContents(path: string): string
export declare function expandDirectory(path: string): Array<FileEntry>
